config/routes.rb
Rails.application.routes.draw do
  get 'design', to: 'pages#design', as: :design
  get 'about', to: 'pages#about', as: :about
  get 'home', to: 'pages#home', as: :home
  get 'living', to: 'pages#living', as: :living
  get 'investor', to: 'pages#investor', as: :investor
  get 'contact', to: 'pages#contact', as: :contact

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def default_url_options
    { host: ENV["HOST"] || "localhost:3000" }
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def design
  end

  def about
  end

  def living
  end

  def home
  end

  def investor
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="alternate" hreflang="fr" href="/fr">

    <%= favicon_link_tag "favicon.ico" %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-123084591-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-123084591-1');
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
  <%= yield(:js) %>
</html>

app/views/pages/about.html.erb
<% content_for(:navbar_class, "navbar-home") %>

<div class="bannerabout banner-headers">
  <div class="banner-content">
    <h1>About us</h1>
  </div>
</div>

<div class="yellow-wrapper">
  <div class="container">
    <h3 id="subtitle">Atypical and unique places where everyone feels at home</h3>
    <div class="row furnished">
      <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1524580708/alexlucie.jpg" alt="Alex&Lucie" class="col-xs-12 col-sm-6 images">
      <div class="col-xs-12 col-sm-6 furnished-content">
        <p>We do our utmost to make our Bernard mates’ life easier.</p>
        <p>No worries about the cleaning, the moving in, or even the bills!</p>
        <p>Live at My Name Is Bernard’s, if you like to meet new people in a comfortable and wonderful place.</p>
      </div>
    </div>

    <h2>Dream Team</h2>
    <div class="profile">
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,q_100/v1524587350/AlexTchidemiansquare.png" alt="alexandra" class="avatar">
          <div class="profile-content">
            <h3>Alexandra Tchidemian</h3>
            <p>Cofounder - Real Estate Manager</p>
            <p>Wondermum ° Sourcing killer ° Rockstar</p>
            <a href="https://www.linkedin.com/in/alexandra-tchidemian-36b19626" target="_blank"><i class="fab fa-linkedin fa-lg"></i></a>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6">
          <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,q_100/v1524587360/luciemoreausquare.jpg" alt="lucie" class="avatar">
          <div class="profile-content">
            <h3>Lucie Moreau</h3>
            <p>Cofounder - Coliving Manager</p>
            <p>Roommate ° Startupper soul ° Dreamer</p>
            <a href="https://www.linkedin.com/in/lucie-moreau-19388248" target="_blank"><i class="fab fa-linkedin fa-lg"></i></a>
          </div>
        </div>
      </div>

    </div>
    <div class="story-sharry">
      <p>"Lucie’s story is part of the beginning of My Name Is Bernard… She is 32 years old and still lives in an house share. she is bill-phobic and moves often. In 9 years, she has moved 13 times. She prefers to share than to own. She doesn’t want to live alone nevertheless she needs her own space. She likes living with other people but she refuses some drawbacks. This digital native is curious about the world surrounding us. She inspires My Name Is Bernard." Alexandra</p>
    </div>

    <h2>Values</h2>
    <div class="row furnished">
      <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1524582432/sharing.jpg" alt="Sharing" class="col-xs-12 col-sm-6 images">
      <div class="col-xs-12 col-sm-6 furnished-content">
        <h3>Sharing</h3>
        <p>Experience diversity</p>
        <p>Reside together while everybody has his/hers own space</p>
        <p>Life is happiness</p>
      </div>
    </div>
    <div class="row furnished righ-card">
      <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1524585448/livingroom2.jpg" alt="Aestheticism" class="col-xs-12 col-sm-6 images mask-right-card">
      <div class="col-xs-12 col-sm-6 furnished-content">
        <h3>Aestheticism</h3>
        <p>A 100% serenity bedroom</p>
        <p>Groovy common spaces</p>
        <p>In distinguished houses</p>
      </div>
      <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1524585448/livingroom2.jpg" alt="Aestheticism" class="col-xs-12 col-sm-6 images display-right-img">
    </div>
    <div class="row furnished">
      <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1524645106/breathe.jpg" alt="Eco consciousness" class="col-xs-12 col-sm-6 images">
      <div class="col-xs-12 col-sm-6 furnished-content">
        <h3>Eco consciousness</h3>
        <p>Selective sorting</p>
        <p>Recycled furniture</p>
        <p>Home automation</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="banner-headers" style="background-image: linear-gradient(-225deg, rgba(200, 200, 200, 0.1) 0%, rgba(0, 0, 0, 0.6) 50%), url('http://res.cloudinary.com/sharry/image/upload/c_scale,w_1174/v1525358146/hello.jpg');">
  <div class="banner-content">
    <h1>Contact us</h1>
    <a href="mailto:hello@sharry.co" title="hello@sharry.co" class="hello">hello@sharry.co</a>
  </div>
</div>

app/views/pages/design.html.erb
<div class="banner-headers bannerdesign">
  <div class="banner-content">
    <h1>Design</h1>
  </div>
</div>

<div class="yellow-wrapper">
  <div class="container">

    <h2>Interior design</h2>
    <h4 id="subtitle2">Space organization is defined on the baseline:</h4>
    <h4 id="subtitle2">live together & on your own,</h4>
    <h4 id="subtitle2">in an amazing uncommon place where everybody feels at home.</h4>
    <div class="interior">
    </div>

    <h2>Ingenious layout</h2>
    <div class="row furnished">
      <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1524670342/bed.jpg" alt="Bedroom" class="col-xs-12 col-sm-6 images">
      <div class="col-xs-12 col-sm-6 furnished-content">
        <h3>Private bedroom</h3>
        <p>Soundproofing</p>
        <p>Closet on wheels</p>
        <p>Lift bed to storage the luggage</p>
        <p>Shower area included</p>
        <p>Cork wall to pin your life</p>
      </div>
    </div>
    <div class="row furnished ">
      <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1524669959/cook.jpg" alt="Kitchen" class="col-xs-12 col-sm-6 images mask-right-card">
      <div class="col-xs-12 col-sm-6 furnished-content">
        <h3>Functional kitchen</h3>
        <p>Glass door fridge to write your name</p>
        <p>Closed personal cupboard</p>
        <p>Stock of common needs</p>
        <p>Quality cooking equipment</p>
      </div>
      <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1524669959/cook.jpg" alt="Kitchen" class="col-xs-12 col-sm-6 images display-right-img">
    </div>
    <div class="row furnished">
      <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1525556897/groupeterrasse.jpg" alt="More" class="col-xs-12 col-sm-6 images">
      <div class="col-xs-12 col-sm-6 furnished-content">
        <h3>Many more</h3>
        <p>Overhead projector</p>
        <p>Work space</p>
        <p>Laundry room</p>
        <p>Terrace</p>
      </div>
    </div>
  </div>
  <%= render 'shared/joinbanner' %>
</div>

app/views/pages/home.html.erb
<div class="banner-header">
  <div class="banner-content">
    <h1>Coliving for urban residents</h1>
    <h3>Private peaceful rooms in enthusiastic homes</h3>
  </div>
</div>

<div class="yellow-wrapper">
  <div class="container">
    <h2>Where?</h2>
    <div class="where">
      <div class="where-content">
        <h3>Lille</h3>
        <p>January, 2019</p>
      </div>
    </div>

    <%= render 'shared/fullyfurnished' %>
    <div class="row furnished">
      <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1525340691/community.jpg" alt="Community" class="col-xs-12 col-sm-6 images">
      <div class="col-xs-12 col-sm-6 furnished-content">
        <h3>Community</h3>
        <p>Home manager</p>
        <p>Events</p>
        <p>e-concierge for more services</p>
        <p>Online booking</p>
      </div>
    </div>

  </div>
</div>
<div id="joinsharry">
</div>
<%= render 'shared/joinbanner' %>

<%= content_for :js do %>
  <script>
  $(function() {
    $("a").on('click', function(event) {
      // Make sure this.hash has a value before overriding default behavior
      if (this.hash !== "")
      {
        // Prevent default anchor click behavior
        event.preventDefault();
        // Store hash
        var hash = this.hash;
        // Using jQuery's animate() method to add smooth page scroll
        // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
        $('html, body').animate({
          scrollTop: $(hash).offset().top
        }, 800, function(){

          // Add hash (#) to URL when done scrolling (default click behavior)
          window.location.hash = hash;
        });
      } // End if
    });
  });
  </script>
<% end %>

app/views/pages/investor.html.erb
<div class="banner-headers bannerinvestor">
  <div class="banner-content">
    <h1>Investor</h1>
  </div>
</div>

<div class="yellow-wrapper">
  <div class="container">
    <h2>What we do</h2>
    <div class="row furnished">
      <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1524667973/partnership.jpg" alt="Partnership" class="col-xs-12 col-sm-6 images">
      <div class="col-xs-12 col-sm-6 furnished-content">
        <p>
          sharry is a real estate company. We develop long-term partnerships with our investors (a 9-year lease agreement).
          From the search of the building, the refurbishment or the construction, to its operation, we offer a turnkey concept.
          sharry manages the property meanwhile its residents live a unique experiment.
        </p>
      </div>
    </div>

    <h2>Assure you a better profitability</h2>
    <div class="row furnished">
      <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1524666759/cityfrance.jpg" alt="Profitability" class="col-xs-12 col-sm-6 mask-right-card images">
      <div class="col-xs-12 col-sm-6 furnished-content">
        <p>The house-sharing market is fast-growing: an increase of 35% in the last 7 years in France.
          sharry rents the property to the owner so that the rent is guaranteed all year during the 9-year lease agreement.
        </p>
        <p>For further information please contact us at:
        </p>
        <div class="">
          <a href="mailto:hello@sharry.co" title="hello@sharry.co">hello@sharry.co</a>
        </div>
      </div>
      <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1524666759/cityfrance.jpg" alt="Profitability" class="col-xs-12 col-sm-6 images display-right-img">
    </div>
    <h2>Manage the property</h2>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <div class="manage-property">
          <h3>Easy booking</h3>
          <p>Online formality to
            reduce paperwork</p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="manage-property">
          <h3>24/7 assistance</h3>
          <p>We solve every day trouble
            (maintenance, billing, etc)</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <div class="manage-property">
          <h3>Handled turnover</h3>
          <p>Waiting list for future colivers
            to maintain 98% of occupancy</p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="manage-property">
          <h3>Digital marketing</h3>
          <p>Strong visibility on social networks
            to strengthen our brand</p>
        </div>
      </div>
    </div>

    <h2>Localization</h2>
    <div class="row furnished">
      <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1524667803/villenuit.jpg" alt="Localization" class="col-xs-12 col-sm-6 images">
      <div class="col-xs-12 col-sm-6 furnished-content">
        <p>City Center</p>
        <p>Near to public transport</p>
        <p>Near to stores, bars & restaurants</p>
      </div>
    </div>
    <!-- <div class="row furnished">
      <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1524669058/roommate.jpg" alt="House share" class="col-xs-12 col-sm-6 images">
      <div class="col-xs-12 col-sm-6 furnished-content">
        <h3>Localization</h3>
        <p>More and more people live in house share. sharry offers them a comfortable and amazing space while investors get a better profitability.</p>
      </div>
    </div> -->

    <h2>Build places to live together</h2>
    <div class="row build">
      <div class="col-xs-12 col-sm-4">
        <div class="profile-content">
          <h3>Mobility</h3>
          <p>+120% Freelance in 10 years</p>
          <p>= 10 times faster than employees</p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="profile-content">
          <h3>Neo family</h3>
          <p>11 million of the 20-39</p>
          <p>year-old youngers live alone</p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="profile-content">
          <h3>Booming market</h3>
          <p>5000 flatshare rooms available</p>
          <p>vs 32000 weekly applications</p>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/pages/living.html.erb
<div class="banner-headers bannerliving">
  <div class="banner-content">
    <h1>Living at My Name Is Bernard's</h1>
  </div>
</div>

<div class="yellow-wrapper">
  <div class="container">
    <h2>My Name Is Bernard’s concept</h2>
      <h3>Live with your alter egos in an distinguished home</h3>
      <p>
        You look for comfort in a furnished place, all included. Living in a house with character delights you.
        You are independent but appreciate the warming atmosphere of roomsharing.
        My Name Is Bernard is in between house sharing and hotel.
      </p>
      <p>
        Here everybody has a private bathroom, while sharing the kitchen and the living-room.
        My Name Is Bernard makes easier the millenial generation life easier respecting their need to « live together but
        separated ».
        The home is an uncommon urban setting where the mate feels at home.
      </p>

      <h2>Compared rent</h2>
      <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8/v1538745284/Compared_rent.jpg" alt="Rent comparison" class="rent-comparison images">


      <%= render 'shared/fullyfurnished' %>
      <h2>Community</h2>
      <div class="row furnished">
        <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1525340691/community.jpg" alt="Community" class="col-xs-12 col-sm-6 images">
        <div class="col-xs-12 col-sm-6 furnished-content">
          <h3>Happy vibes together</h3>
          <p>Home manager</p>
          <p>Events</p>
          <p>Millenial tools like whatsapp & slack</p>
        </div>
      </div>

      <h2>Services</h2>
      <div class="row furnished">
        <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1525340493/telephone.jpg" alt="E-concierge" class="col-xs-12 col-sm-6 images mask-right-card">
        <div class="col-xs-12 col-sm-6 furnished-content">
          <h3>All online</h3>
          <p>Booking & rent contract</p>
          <p>E-concierge:</p>
          <p>Room cleaning, bedlinen rental...</p>
        </div>
        <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1525340493/telephone.jpg" alt="E-concierge" class="col-xs-12 col-sm-6 images display-right-img">
      </div>

  </div>
  <%= render 'shared/joinbanner' %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-3 footer-title">
        <div>
          <h4>MY NAME IS BERNARD</h4>
        </div>
          <p>Euratechnologies</p>
          <p>165 Avenue de Bretagne</p>
          <p>59000 Lille</p>
          <p>+33 (0)3 66 88 04 48</p>
        </div>
      <div class="col-xs-12 col-sm-3">
        <div class="footer-title">
          <h4>Housing</h4>
        </div>
        <div class="footer-links">
          <%= link_to "Living at MNIB's", living_path %>
        </div>
        <div class="footer-links">
          <%= link_to "Design", design_path %>
        </div>
        <div class="footer-links">
          <%= link_to "Investor", investor_path %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-3">
        <div class="footer-title">
          <h4>Company</h4>
        </div>
        <div class="footer-links">
          <%= link_to "Join MNIB", home_path(@home, anchor: "joinsharry") %>
        </div>
        <div class="footer-links">
          <%= link_to "About us", about_path %>
        </div>
        <div class="footer-links">
          <a href="mailto:hello@mynameisbernard.com" title="hello@mynameisbernard.com">Contact us</a>
        </div>
        <div class="footer-links">
          <a href="https://www.facebook.com/mynameisbernardcoliving/" target="_blank">
            <i class="fab fa-facebook fa-lg"></i>
          </a>
          <a href="https://www.instagram.com/my_name_is_bernard/" target="_blank">
            <i class="fab fa-instagram fa-lg"></i>
          </a>
          <!-- <a href="#" target="_blank"><i class="fab fa-medium fa-lg"></i></a> -->
        </div>
      </div>
      <div class="col-xs-12 col-sm-3">
        <div class="footer-title">
          <h4>Partners</h4>
        </div>
        <div class="footer-links">
          <a href="https://www.euratechnologies.com" target="_blank" class="partner-brand">
            <%= image_tag "https://www.euratechnologies.com/content/themes/euratechnologies/assets/img/euratechnologies-logo-white.svg", id: "logo" %>
          </a>
          <a href="https://www.levillagebyca.com/fr/village/nord-de-france" target="_blank" class="partner-brand">
            <%= image_tag "https://www.levillagebyca.com/themes/custom/levillage/logo-black.svg", id: "logoca" %>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_fullyfurnished.html.erb
<h2>Fully furnished home</h2>
<div class="row furnished">
  <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1524498180/bedroom.jpg" alt="Bedroom" class="col-xs-12 col-sm-6 images">
  <div class="col-xs-12 col-sm-6 furnished-content">
    <h3>Private bedroom</h3>
    <p>Includes a bathroom</p>
    <p>Peaceful design</p>
    <p>Sheets optional for 100% comfort</p>
    <p>High speed wifi & Netflix</p>
  </div>
</div>

<div class="row furnished">
  <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1524497810/interiordesign.jpg" alt="Common space" class="col-xs-12 col-sm-6 images mask-right-card">
  <div class="col-xs-12 col-sm-6 furnished-content">
    <h3>Playful common spaces</h3>
    <p>Kitchen & trendy living room</p>
    <p>Terrace for sunny days</p>
    <p>Eco-conscious environment</p>
    <p>Weekly cleaning</p>
  </div>
  <img src="http://res.cloudinary.com/sharry/image/upload/c_scale,dpr_auto,fl_png8,h_427,q_100/v1524497810/interiordesign.jpg" alt="Common space" class="col-xs-12 col-sm-6 images display-right-img">
</div>

app/views/shared/_joinbanner.html.erb
<div class="join-banner">
  <div class="join-content">
    <h1>Ready to move in?</h1>
    <h4>Stay tuned</h4>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-sm-offset-4">

        <!-- <form class="form-inline">
          <div class="form-group">
            <label for="email"></label>
            <input type="text" name="" placeholder="joey@friends.com" class="form-control" id="email">
          </div>
          <input type="submit" name="" value="Send" class="btn-cta">
        </form> -->

        <!-- Begin MailChimp Signup Form -->
        <div id="mc_embed_signup">
        <form action="https://sharry.us14.list-manage.com/subscribe/post?u=700512906302f4c9b22fa726d&amp;id=99ffcdcd5d" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
          <div class="form-group" id="mc_embed_signup_scroll">
            <div class="mc-field-group">
            	<label for="mce-EMAIL"></label>
            	<input type="email" placeholder="sheldon@cooper.com" value="" name="EMAIL" class="subemail form-control input-sm required email" id=" mce-EMAIL">
            </div>
          	<div id="mce-responses" class="clear">
          		<div class="response" id="mce-error-response" style="display:none"></div>
          		<div class="response" id="mce-success-response" style="display:none"></div>
          	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
            <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_700512906302f4c9b22fa726d_99ffcdcd5d" tabindex="-1" value=""></div>
            <div class="clear"><input type="submit" value="Send" name="subscribe" id="mc-embedded-subscribe" class="button btn-cta"></div>
          </div>
        </form>
        </div>
        <!--End mc_embed_signup-->

      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-fixed-top">
  <div class="navbar-wagon navbar-home">
    <!-- Logo -->
    <a href="/" class="navbar-wagon-brand">
      <%= image_tag "logo.png", id: "logo" %>
      <!-- <p class="navbar-wagon-link navbar-wagon-link:hover sharry-brand">sharry</p> -->
    </a>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <%= link_to "Living at MNIB's", living_path, class: "navbar-wagon-item navbar-wagon-link navbar-wagon-link:hover" %>
      <%= link_to "Design", design_path, class: "navbar-wagon-item navbar-wagon-link navbar-wagon-link:hover" %>
      <%= link_to "About us", about_path, class: "navbar-wagon-item navbar-wagon-link navbar-wagon-link:hover" %>
      <%= link_to "Join MNIB", home_path(@home, anchor: "joinsharry"), class: "navbar-wagon-link navbar-wagon-link:hover btn-cta join" %>
    </div>

    <!-- Dropdown appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Living at MNIB's", living_path %></li>
          <li><%= link_to "Design", design_path %></li>
          <li><%= link_to "About us", about_path %></li>
          <li><%= link_to "Join MNIB", home_path(@home, anchor: "joinsharry") %></li>
        </ul>
      </div>
    </div>

  </div>
</div>